services:
  password-generator:
    image: ghcr.io/jeanleles/passwordgenerator:latest
    container_name: password-generator
    restart: unless-stopped

    networks:
      - webnetwork

networks:
  webnetwork:
    external: true
